/* ==========================================================================
   Class 8 English MCQ Practice — PECTTA 2026-27 Pattern
   GHS 124NB | M Ijaz
   10 Papers x 25 MCQs (50 marks each), Passing = 33%
   ========================================================================== */

const APP = {
  studentName: "",
  currentPaper: null,
  currentIndex: 0,
  answers: [],
  startTime: null,
};

/* ---------------------------- QUESTION POOLS ----------------------------- */

const nounPool = [
  { q: "Choose the common noun: 'The ___ ran across the field.'", options: ["Karachi", "dog", "Ali", "Monday"], answer: 1 },
  { q: "Identify the proper noun in: 'Sara visited Lahore last week.'", options: ["visited", "Sara", "week", "last"], answer: 1 },
  { q: "'A herd of cattle grazed nearby.' The word 'herd' is a:", options: ["Common noun", "Collective noun", "Abstract noun", "Proper noun"], answer: 1 },
  { q: "Which word is an abstract noun?", options: ["Table", "Honesty", "River", "Teacher"], answer: 1 },
  { q: "'Milk is good for health.' 'Milk' is a:", options: ["Countable noun", "Material noun", "Collective noun", "Proper noun"], answer: 1 },
  { q: "Choose the collective noun: 'A ___ of sheep entered the barn.'", options: ["group", "flock", "team", "family"], answer: 1 },
  { q: "'Kindness is a virtue.' The noun 'Kindness' is:", options: ["Concrete", "Abstract", "Collective", "Material"], answer: 1 },
  { q: "Which is a proper noun?", options: ["city", "river", "Pakistan", "mountain"], answer: 2 },
  { q: "'The jury gave its verdict.' 'Jury' is a:", options: ["Proper noun", "Collective noun", "Material noun", "Abstract noun"], answer: 1 },
  { q: "Identify the material noun: 'The ring is made of gold.'", options: ["ring", "made", "gold", "is"], answer: 2 },
  { q: "Which word is a common noun?", options: ["Ahmed", "Friday", "boy", "Everest"], answer: 2 },
  { q: "'Bravery' is an example of a/an:", options: ["Common noun", "Abstract noun", "Proper noun", "Collective noun"], answer: 1 },
  { q: "Choose the correct proper noun.", options: ["school", "river", "Islamabad", "book"], answer: 2 },
  { q: "'A bunch of keys' — 'bunch' is a:", options: ["Abstract noun", "Collective noun", "Material noun", "Proper noun"], answer: 1 },
  { q: "Which noun cannot be counted?", options: ["books", "water", "pens", "chairs"], answer: 1 },
  { q: "'The committee has approved the plan.' 'Committee' is a:", options: ["Common noun", "Collective noun", "Proper noun", "Material noun"], answer: 1 },
  { q: "Identify the abstract noun: 'His honesty impressed everyone.'", options: ["everyone", "impressed", "honesty", "His"], answer: 2 },
  { q: "Which is a material noun?", options: ["Iron", "Beauty", "Team", "Lahore"], answer: 0 },
  { q: "'The class is studying grammar.' 'Class' here is a:", options: ["Proper noun", "Collective noun", "Abstract noun", "Material noun"], answer: 1 },
  { q: "Choose the abstract noun.", options: ["Chair", "Sugar", "Wisdom", "Karim"], answer: 2 },
];

const verbPool = [
  { q: "Identify the verb: 'The children play in the park.'", options: ["children", "play", "park", "the"], answer: 1 },
  { q: "'She has finished her homework.' The auxiliary verb is:", options: ["finished", "her", "has", "homework"], answer: 2 },
  { q: "Choose the transitive verb: 'He kicked the ball.'", options: ["He", "kicked", "the", "ball"], answer: 1 },
  { q: "Which is an intransitive verb?", options: ["eats", "sleeps", "reads", "writes"], answer: 1 },
  { q: "'They can swim very well.' 'Can' is a:", options: ["Main verb", "Modal verb", "Linking verb", "Transitive verb"], answer: 1 },
  { q: "Identify the linking verb: 'The soup smells delicious.'", options: ["soup", "smells", "delicious", "the"], answer: 1 },
  { q: "'Must' is an example of a:", options: ["Modal verb", "Main verb", "Linking verb", "Transitive verb"], answer: 0 },
  { q: "Choose the correct verb form: 'He ___ to school daily.'", options: ["go", "goes", "going", "gone"], answer: 1 },
  { q: "'The teacher is explaining the lesson.' The main verb is:", options: ["is", "explaining", "lesson", "the"], answer: 1 },
  { q: "Which sentence has a transitive verb?", options: ["Birds fly.", "She sings a song.", "He sleeps.", "The sun rises."], answer: 1 },
  { q: "Identify the auxiliary verb: 'They were playing football.'", options: ["playing", "football", "were", "They"], answer: 2 },
  { q: "Choose the modal verb: 'You should obey your elders.'", options: ["obey", "should", "elders", "your"], answer: 1 },
  { q: "'The cake tastes sweet.' The verb 'tastes' is a:", options: ["Transitive verb", "Linking verb", "Modal verb", "Auxiliary verb"], answer: 1 },
  { q: "Choose the correct verb: 'She ___ her homework yesterday.'", options: ["do", "does", "did", "doing"], answer: 2 },
  { q: "Identify the intransitive verb: 'The baby cried.'", options: ["The", "baby", "cried", "none"], answer: 2 },
  { q: "'Will' is used to show:", options: ["Past action", "Future action", "Present action", "Habit"], answer: 1 },
  { q: "Choose the correct sentence.", options: ["He don't like tea.", "He doesn't likes tea.", "He doesn't like tea.", "He not like tea."], answer: 2 },
  { q: "'The dog barks loudly.' The verb is:", options: ["dog", "barks", "loudly", "the"], answer: 1 },
  { q: "Identify the modal verb: 'I may come tomorrow.'", options: ["may", "come", "tomorrow", "I"], answer: 0 },
  { q: "Choose the transitive verb: 'She wrote a letter.'", options: ["She", "wrote", "letter", "a"], answer: 1 },
];

const prepPool = [
  { q: "Fill in the blank: 'The book is ___ the table.'", options: ["on", "in", "at", "by"], answer: 0 },
  { q: "'She arrived ___ 5 o'clock.'", options: ["in", "on", "at", "for"], answer: 2 },
  { q: "'He was born ___ 2012.'", options: ["at", "in", "on", "by"], answer: 1 },
  { q: "'The cat is hiding ___ the bed.'", options: ["under", "at", "to", "for"], answer: 0 },
  { q: "'We walked ___ the park.'", options: ["through", "at", "on", "by"], answer: 0 },
  { q: "'This gift is ___ you.'", options: ["at", "for", "on", "with"], answer: 1 },
  { q: "'She lives ___ Multan.'", options: ["in", "at", "on", "to"], answer: 0 },
  { q: "'The train departs ___ platform 2.'", options: ["at", "on", "from", "in"], answer: 1 },
  { q: "'He divided the cake ___ four pieces.'", options: ["into", "in", "at", "on"], answer: 0 },
  { q: "'They are sitting ___ the table.'", options: ["around", "at", "on", "to"], answer: 0 },
  { q: "'She is good ___ mathematics.'", options: ["in", "at", "on", "with"], answer: 1 },
  { q: "'The plane flew ___ the clouds.'", options: ["above", "at", "on", "in"], answer: 0 },
  { q: "'He apologized ___ his mistake.'", options: ["for", "at", "to", "on"], answer: 0 },
  { q: "'She has been waiting ___ two hours.'", options: ["since", "for", "from", "at"], answer: 1 },
  { q: "'I have known him ___ 2019.'", options: ["for", "since", "at", "in"], answer: 1 },
  { q: "'The keys are ___ the drawer.'", options: ["inside", "at", "to", "for"], answer: 0 },
  { q: "'He jumped ___ the wall.'", options: ["over", "at", "on", "to"], answer: 0 },
  { q: "'She was angry ___ her brother.'", options: ["with", "at", "on", "for"], answer: 0 },
  { q: "'The shop is ___ the corner.'", options: ["at", "on", "in", "to"], answer: 0 },
  { q: "'He is afraid ___ dogs.'", options: ["of", "from", "at", "with"], answer: 0 },
];

const pronPool = [
  { q: "Identify the pronoun: 'She is my best friend.'", options: ["best", "friend", "She", "my"], answer: 2 },
  { q: "'This is my book.' 'my' is a:", options: ["Personal pronoun", "Possessive pronoun", "Reflexive pronoun", "Relative pronoun"], answer: 1 },
  { q: "Choose the reflexive pronoun: 'He hurt himself.'", options: ["He", "hurt", "himself", "none"], answer: 2 },
  { q: "'The boy who won the race is my cousin.' 'who' is a:", options: ["Personal pronoun", "Relative pronoun", "Interrogative pronoun", "Demonstrative pronoun"], answer: 1 },
  { q: "'Who is knocking at the door?' 'Who' is a/an:", options: ["Interrogative pronoun", "Relative pronoun", "Reflexive pronoun", "Possessive pronoun"], answer: 0 },
  { q: "Choose the demonstrative pronoun: 'This is not fair.'", options: ["This", "is", "not", "fair"], answer: 0 },
  { q: "'They helped each other.' 'each other' is a:", options: ["Reciprocal pronoun", "Reflexive pronoun", "Relative pronoun", "Personal pronoun"], answer: 0 },
  { q: "'Somebody left the door open.' 'Somebody' is a:", options: ["Indefinite pronoun", "Personal pronoun", "Relative pronoun", "Demonstrative pronoun"], answer: 0 },
  { q: "Choose the possessive pronoun: 'This pen is mine.'", options: ["This", "pen", "is", "mine"], answer: 3 },
  { q: "'I taught myself to cook.' 'myself' is a:", options: ["Reflexive pronoun", "Personal pronoun", "Relative pronoun", "Interrogative pronoun"], answer: 0 },
  { q: "'Those are my shoes.' 'Those' is a:", options: ["Personal pronoun", "Demonstrative pronoun", "Relative pronoun", "Indefinite pronoun"], answer: 1 },
  { q: "Identify the personal pronoun: 'We are going to school.'", options: ["going", "school", "We", "to"], answer: 2 },
  { q: "'Which of these is your bag?' 'Which' is a:", options: ["Interrogative pronoun", "Relative pronoun", "Reflexive pronoun", "Demonstrative pronoun"], answer: 0 },
  { q: "'Everyone enjoyed the trip.' 'Everyone' is a:", options: ["Indefinite pronoun", "Personal pronoun", "Reflexive pronoun", "Relative pronoun"], answer: 0 },
  { q: "Choose the correct pronoun: '___ went to the market yesterday.'", options: ["Him", "He", "His", "Himself"], answer: 1 },
  { q: "'The pen that I lost was expensive.' 'that' is a:", options: ["Relative pronoun", "Personal pronoun", "Demonstrative pronoun", "Indefinite pronoun"], answer: 0 },
  { q: "'She looked at herself in the mirror.' 'herself' is a:", options: ["Personal pronoun", "Reflexive pronoun", "Relative pronoun", "Possessive pronoun"], answer: 1 },
  { q: "'No one answered the call.' 'No one' is a:", options: ["Indefinite pronoun", "Demonstrative pronoun", "Personal pronoun", "Relative pronoun"], answer: 0 },
  { q: "Choose the correct object pronoun: 'Give the book to ___.'", options: ["he", "him", "his", "himself"], answer: 1 },
  { q: "'These are the best days of my life.' 'These' is a:", options: ["Demonstrative pronoun", "Personal pronoun", "Relative pronoun", "Indefinite pronoun"], answer: 0 },
];

const genderPool = [
  { q: "The feminine gender of 'King' is:", options: ["Queen", "Princess", "Duchess", "Lady"], answer: 0 },
  { q: "The masculine gender of 'Actress' is:", options: ["Actor", "Actress", "Hero", "Manager"], answer: 0 },
  { q: "'Tiger' — the feminine form is:", options: ["Tigress", "Lioness", "She-tiger", "Cub"], answer: 0 },
  { q: "'Cow' is the feminine of:", options: ["Ox", "Bull", "Calf", "Buffalo"], answer: 1 },
  { q: "Which word denotes common gender?", options: ["Teacher", "King", "Queen", "Actress"], answer: 0 },
  { q: "'Rooster' is the masculine of:", options: ["Duck", "Hen", "Chick", "Goose"], answer: 1 },
  { q: "Which is a neuter gender word?", options: ["Boy", "Book", "Girl", "Man"], answer: 1 },
  { q: "The feminine of 'Waiter' is:", options: ["Waitress", "Woman", "Lady", "Maid"], answer: 0 },
  { q: "'Nephew' is the masculine of:", options: ["Niece", "Sister", "Aunt", "Cousin"], answer: 0 },
  { q: "The feminine of 'Hero' is:", options: ["Heroine", "Actress", "Lady", "Princess"], answer: 0 },
  { q: "'Bridegroom' is the masculine of:", options: ["Bride", "Wife", "Woman", "Sister"], answer: 0 },
  { q: "Which word is masculine gender?", options: ["Wolf", "She-wolf", "Vixen", "Duck"], answer: 0 },
  { q: "The feminine of 'Host' is:", options: ["Hostess", "Guest", "Landlady", "Madam"], answer: 0 },
  { q: "'Stallion' is the masculine of a:", options: ["Mare", "Cow", "Ewe", "Doe"], answer: 0 },
  { q: "Which word denotes a common gender noun?", options: ["Parent", "Uncle", "Aunt", "Duke"], answer: 0 },
  { q: "The feminine of 'Emperor' is:", options: ["Empress", "Queen", "Princess", "Duchess"], answer: 0 },
  { q: "'Gander' is the masculine of:", options: ["Goose", "Hen", "Duck", "Peahen"], answer: 0 },
  { q: "Which word is a neuter gender noun?", options: ["Table", "Man", "Woman", "Boy"], answer: 0 },
  { q: "The feminine of 'Wizard' is:", options: ["Witch", "Fairy", "Queen", "Lady"], answer: 0 },
  { q: "'Drake' is the masculine of:", options: ["Duck", "Hen", "Goose", "Swan"], answer: 0 },
];

const spPool = [
  { q: "Choose the plural of 'child'.", options: ["childs", "childes", "children", "childies"], answer: 2 },
  { q: "The plural of 'mouse' is:", options: ["mouses", "mice", "meece", "mices"], answer: 1 },
  { q: "Choose the plural of 'city'.", options: ["citys", "cities", "citties", "cityes"], answer: 1 },
  { q: "The plural of 'knife' is:", options: ["knifes", "knives", "kniefs", "knifies"], answer: 1 },
  { q: "Choose the plural of 'sheep'.", options: ["sheeps", "sheep", "sheepes", "sheepies"], answer: 1 },
  { q: "The plural of 'foot' is:", options: ["foots", "feets", "feet", "footes"], answer: 2 },
  { q: "Choose the plural of 'tomato'.", options: ["tomatos", "tomatoes", "tomatoies", "tomatoe"], answer: 1 },
  { q: "The plural of 'man' is:", options: ["mans", "men", "mens", "manes"], answer: 1 },
  { q: "Choose the plural of 'leaf'.", options: ["leafs", "leaves", "leafes", "leves"], answer: 1 },
  { q: "The plural of 'tooth' is:", options: ["tooths", "teeth", "teeths", "toothes"], answer: 1 },
  { q: "Choose the plural of 'box'.", options: ["boxs", "boxes", "boxies", "boxen"], answer: 1 },
  { q: "The plural of 'goose' is:", options: ["gooses", "geese", "geeses", "goosies"], answer: 1 },
  { q: "Choose the plural of 'baby'.", options: ["babys", "babies", "babyes", "babbies"], answer: 1 },
  { q: "The plural of 'ox' is:", options: ["oxes", "oxen", "oxs", "oxies"], answer: 1 },
  { q: "Choose the plural of 'fish' (general).", options: ["fishs", "fishes", "fish", "fishies"], answer: 2 },
  { q: "The plural of 'wife' is:", options: ["wifes", "wives", "wifies", "wifs"], answer: 1 },
  { q: "Choose the plural of 'story'.", options: ["storys", "stories", "storries", "storyes"], answer: 1 },
  { q: "The plural of 'deer' is:", options: ["deers", "deer", "deeres", "deeries"], answer: 1 },
  { q: "Choose the plural of 'potato'.", options: ["potatos", "potatoes", "potatoies", "potatoe"], answer: 1 },
  { q: "The singular of 'geese' is:", options: ["goose", "gooses", "geese", "geeses"], answer: 0 },
];

/* Tenses — 5 per paper x 10 papers = 50, cycling all 12 types */
const tensePool = [
  { q: "'She ___ (write) a letter every day.' (Present Simple)", options: ["write", "writes", "wrote", "writing"], answer: 1 },
  { q: "'They ___ (play) football right now.' (Present Continuous)", options: ["play", "plays", "are playing", "played"], answer: 2 },
  { q: "'He ___ (finish) his homework already.' (Present Perfect)", options: ["has finished", "finished", "finishes", "is finishing"], answer: 0 },
  { q: "'I ___ (study) for three hours now.' (Present Perfect Continuous)", options: ["have been studying", "study", "studied", "am studying"], answer: 0 },
  { q: "'She ___ (visit) her grandmother yesterday.' (Past Simple)", options: ["visits", "visited", "was visiting", "has visited"], answer: 1 },
  { q: "'They ___ (watch) TV when I called.' (Past Continuous)", options: ["watched", "were watching", "watch", "have watched"], answer: 1 },
  { q: "'He ___ (leave) before I arrived.' (Past Perfect)", options: ["had left", "left", "has left", "was leaving"], answer: 0 },
  { q: "'We ___ (wait) for an hour before the bus came.' (Past Perfect Continuous)", options: ["had been waiting", "waited", "were waiting", "have waited"], answer: 0 },
  { q: "'I ___ (call) you tomorrow.' (Future Simple)", options: ["will call", "call", "am calling", "called"], answer: 0 },
  { q: "'She ___ (travel) this time next week.' (Future Continuous)", options: ["will be traveling", "travels", "traveled", "has traveled"], answer: 0 },
  { q: "'By next year, he ___ (complete) his degree.' (Future Perfect)", options: ["will have completed", "completes", "completed", "will complete"], answer: 0 },
  { q: "'By evening, we ___ (work) for ten hours.' (Future Perfect Continuous)", options: ["will have been working", "will work", "worked", "work"], answer: 0 },
  { q: "'The sun ___ (rise) in the east.' (Present Simple)", options: ["rise", "rises", "rose", "rising"], answer: 1 },
  { q: "'Look! The baby ___ (sleep).' (Present Continuous)", options: ["sleeps", "is sleeping", "slept", "sleep"], answer: 1 },
  { q: "'We ___ (never/see) such a big elephant.' (Present Perfect)", options: ["have never seen", "never see", "never saw", "are never seeing"], answer: 0 },
  { q: "'She ___ (learn) English for five years.' (Present Perfect Continuous)", options: ["has been learning", "learns", "learned", "is learning"], answer: 0 },
  { q: "'He ___ (go) to school yesterday.' (Past Simple)", options: ["goes", "went", "was going", "has gone"], answer: 1 },
  { q: "'I ___ (read) a book when the light went off.' (Past Continuous)", options: ["read", "was reading", "have read", "reads"], answer: 1 },
  { q: "'The train ___ (leave) before we reached the station.' (Past Perfect)", options: ["had left", "left", "leaves", "was leaving"], answer: 0 },
  { q: "'She ___ (cook) for two hours before guests arrived.' (Past Perfect Continuous)", options: ["had been cooking", "cooked", "was cooking", "cooks"], answer: 0 },
  { q: "'They ___ (arrive) tomorrow morning.' (Future Simple)", options: ["will arrive", "arrive", "arrived", "are arriving"], answer: 0 },
  { q: "'At 8 pm, I ___ (have) dinner.' (Future Continuous)", options: ["will be having", "have", "had", "will have"], answer: 0 },
  { q: "'By the time you arrive, I ___ (finish) cooking.' (Future Perfect)", options: ["will have finished", "finish", "finished", "will finish"], answer: 0 },
  { q: "'By next month, she ___ (teach) here for ten years.' (Future Perfect Continuous)", options: ["will have been teaching", "will teach", "teaches", "taught"], answer: 0 },
  { q: "'Water ___ (boil) at 100°C.' (Present Simple)", options: ["boil", "boils", "boiled", "boiling"], answer: 1 },
  { q: "'He ___ (do) his homework at the moment.' (Present Continuous)", options: ["does", "is doing", "did", "do"], answer: 1 },
  { q: "'I ___ (lose) my pen. I can't find it.' (Present Perfect)", options: ["have lost", "lost", "lose", "am losing"], answer: 0 },
  { q: "'They ___ (play) cricket since morning.' (Present Perfect Continuous)", options: ["have been playing", "play", "played", "are playing"], answer: 0 },
  { q: "'She ___ (buy) a new dress last week.' (Past Simple)", options: ["buys", "bought", "was buying", "has bought"], answer: 1 },
  { q: "'While I ___ (cook), the phone rang.' (Past Continuous)", options: ["cooked", "was cooking", "cook", "have cooked"], answer: 1 },
  { q: "'She ___ (finish) her work before he called.' (Past Perfect)", options: ["had finished", "finished", "finishes", "was finishing"], answer: 0 },
  { q: "'He ___ (run) for an hour before he stopped.' (Past Perfect Continuous)", options: ["had been running", "ran", "was running", "runs"], answer: 0 },
  { q: "'We ___ (meet) again next Friday.' (Future Simple)", options: ["will meet", "meet", "met", "are meeting"], answer: 0 },
  { q: "'This time tomorrow, they ___ (fly) to London.' (Future Continuous)", options: ["will be flying", "fly", "flew", "will fly"], answer: 0 },
  { q: "'By 2030, scientists ___ (develop) new medicines.' (Future Perfect)", options: ["will have developed", "develop", "developed", "will develop"], answer: 0 },
  { q: "'By June, he ___ (work) here for two years.' (Future Perfect Continuous)", options: ["will have been working", "will work", "works", "worked"], answer: 0 },
  { q: "'Birds ___ (fly) in the sky.' (Present Simple)", options: ["fly", "flies", "flew", "flying"], answer: 0 },
  { q: "'She ___ (talk) on the phone now.
